package com.whichcontact.rest.DigitalIndia;

/**
 * @author TS001127
 *
 */
public class Records {

	public String REGISTRAROFCOMPANIES;
	public String COMPANYNAME;
	public String CORPORATEIDENTIFICATIONNUMBER;
	public String PRINCIPALBUSINESSACTIVITYASPERCIN;
	public String AUTHORIZEDCAPITAL;
	public String REGISTEREDSTATE;
	public String PAIDUPCAPITAL;

	public String REGISTEREDOFFICEADDRESS;

	public String getPAIDUPCAPITAL() {
		return PAIDUPCAPITAL;
	}

	public void setPAIDUPCAPITAL(String pAIDUPCAPITAL) {
		PAIDUPCAPITAL = pAIDUPCAPITAL;
	}

	public String getREGISTEREDOFFICEADDRESS() {
		return REGISTEREDOFFICEADDRESS;
	}

	public void setREGISTEREDOFFICEADDRESS(String rEGISTEREDOFFICEADDRESS) {
		REGISTEREDOFFICEADDRESS = rEGISTEREDOFFICEADDRESS;
	}

	public String getREGISTRAROFCOMPANIES() {
		return REGISTRAROFCOMPANIES;
	}

	public void setREGISTRAROFCOMPANIES(String rEGISTRAROFCOMPANIES) {
		REGISTRAROFCOMPANIES = rEGISTRAROFCOMPANIES;
	}

	public String getCOMPANYNAME() {
		return COMPANYNAME;
	}

	public void setCOMPANYNAME(String cOMPANYNAME) {
		COMPANYNAME = cOMPANYNAME;
	}

	public String getCORPORATEIDENTIFICATIONNUMBER() {
		return CORPORATEIDENTIFICATIONNUMBER;
	}

	public void setCORPORATEIDENTIFICATIONNUMBER(String cORPORATEIDENTIFICATIONNUMBER) {
		CORPORATEIDENTIFICATIONNUMBER = cORPORATEIDENTIFICATIONNUMBER;
	}

	public String getPRINCIPALBUSINESSACTIVITYASPERCIN() {
		return PRINCIPALBUSINESSACTIVITYASPERCIN;
	}

	public void setPRINCIPALBUSINESSACTIVITYASPERCIN(String pRINCIPALBUSINESSACTIVITYASPERCIN) {
		PRINCIPALBUSINESSACTIVITYASPERCIN = pRINCIPALBUSINESSACTIVITYASPERCIN;
	}

	public String getAUTHORIZEDCAPITAL() {
		return AUTHORIZEDCAPITAL;
	}

	public void setAUTHORIZEDCAPITAL(String aUTHORIZEDCAPITAL) {
		AUTHORIZEDCAPITAL = aUTHORIZEDCAPITAL;
	}

	public String getREGISTEREDSTATE() {
		return REGISTEREDSTATE;
	}

	public void setREGISTEREDSTATE(String rEGISTEREDSTATE) {
		REGISTEREDSTATE = rEGISTEREDSTATE;
	}

}